name: Build & Push Images

on:
  push:
    branches: [ "main" ]
    tags:     [ "v*" ]
    paths:
      - 'front-end/**'
      - 'back-end/**'
      - 'compose.prod.yml'
      - '.github/workflows/build.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_NAMESPACE: ${{ secrets.DOCKERHUB_NAMESPACE }}
      SECRET_COOKIE_PASSWORD: ${{ secrets.SECRET_COOKIE_PASSWORD }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: web,   repo: clms-web,   context: ./front-end, file: ./front-end/Dockerfile,                       needsSecret: true  }
          - { name: api,   repo: clms-api,   context: .,           file: ./back-end/dockerfiles/php.app.dockerfile,   needsSecret: false }
          - { name: proxy, repo: clms-proxy, context: ./back-end,  file: ./back-end/dockerfiles/nginx.app.dockerfile, needsSecret: false }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine build platforms
        id: plat
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == refs/tags/* ]]; then
            echo "platforms=linux/amd64,linux/arm64" >> "$GITHUB_OUTPUT"
          else
            echo "platforms=linux/amd64" >> "$GITHUB_OUTPUT"
          fi

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (${{ matrix.name }})
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/${{ matrix.repo }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=tag

      - name: Build and push (with secret)
        if: ${{ matrix.needsSecret == true }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          platforms: ${{ steps.plat.outputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}
          provenance: false
          secrets: |
            id=secret_cookie_password,env=SECRET_COOKIE_PASSWORD

      - name: Build and push
        if: ${{ matrix.needsSecret == false }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          platforms: ${{ steps.plat.outputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.name }}
          provenance: false
